NAME		=	interface
SRC			=	main.cpp AMateria.cpp Character.cpp Cure.cpp Ice.cpp \
				MateriaSource.cpp main.cpp
OBJS		= $(SRC:.cpp=.o)

CXX			= c++
CPPFLAGS	= -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $^ -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all
